#MAKEFILE OF BATTLESHIP-TCF

#DEFINIZIONE DEL COMPILATORE
CXX	= g++
#IDENTIFICA SE COMPILARE PER UNIX O PER WINDOWS
DR = UNIX
#OPZIONI DEL COMPILATORE
CFLAGS = -pipe -std=c++14 -O0 -pedantic -Wall -D$(DR)
#IDENTIFICA IL PATH IN CUI MAKE DEVE CERCARE
VPATH = source
#IDENTIFICA TUTTI I FILE DA CUI IL PROGRAMMA DIPENDE
OBJECTS = main.o Ship.o Player.o Point.o Battleship.o Carrier.o Cruiser.o \
		  Destroyer.o ShipFactory.o Graphic.o Error.o
#IDENTIFICA IL NUMERO DI JOBS PER MAKE
#(NON UTILIZZARE PIÙ DEL NUMERO DI CORES DISPONIBILI)
CPUCORES = 4

all:
	@echo -e "\033[1;34m"::COSTRUISCO I BINARI NECESSARI..." \033[0m"
	$(MAKE) -j $(CPUCORES) battleship-tcf
	@echo -e "\033[1;34m"::COMPILAZIONE TERMINATA" \033[0m"

#ISTRUZIONI PER L'ESEGUIBILE
battleship-tcf:	$(OBJECTS)
	 @echo -e "\033[1;34m"::COSTRUISCO L "'" ESEGUIBILE" \033[0m"
	 $(CXX) $(CFLAGS) $(OBJECTS) -o $@

#ISTRUZIONI PER COMPILARE LE VARIE CLASSI
%.o: %.cpp
	 $(CXX) $(CFLAGS) -c $^ -o $@
	 
#ISTRUZIONI PER ELIMINARE I FILE *.o
clean: 
	 @echo -e "\033[1;34m"::RIMOZIONE DEI BINARI IN CORSO..." \033[0m"
	 $(RM) $(OBJECTS)
	 @echo -e "\033[1;34m"::RIMOZIONE TERMINATA" \033[0m"